/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './renderer/src/routes/__root'
import { Route as IndexRouteImport } from './renderer/src/routes/index'
import { Route as ProjectsProjectPathRouteImport } from './renderer/src/routes/projects/$projectPath'
import { Route as ProjectsAIFileProjectPathRouteImport } from './renderer/src/routes/projects/AI/$file.$projectPath'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectPathRoute = ProjectsProjectPathRouteImport.update({
  id: '/projects/$projectPath',
  path: '/projects/$projectPath',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsAIFileProjectPathRoute =
  ProjectsAIFileProjectPathRouteImport.update({
    id: '/projects/AI/$file/$projectPath',
    path: '/projects/AI/$file/$projectPath',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$projectPath': typeof ProjectsProjectPathRoute
  '/projects/AI/$file/$projectPath': typeof ProjectsAIFileProjectPathRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/$projectPath': typeof ProjectsProjectPathRoute
  '/projects/AI/$file/$projectPath': typeof ProjectsAIFileProjectPathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/$projectPath': typeof ProjectsProjectPathRoute
  '/projects/AI/$file/$projectPath': typeof ProjectsAIFileProjectPathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects/$projectPath' | '/projects/AI/$file/$projectPath'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects/$projectPath' | '/projects/AI/$file/$projectPath'
  id:
    | '__root__'
    | '/'
    | '/projects/$projectPath'
    | '/projects/AI/$file/$projectPath'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsProjectPathRoute: typeof ProjectsProjectPathRoute
  ProjectsAIFileProjectPathRoute: typeof ProjectsAIFileProjectPathRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectPath': {
      id: '/projects/$projectPath'
      path: '/projects/$projectPath'
      fullPath: '/projects/$projectPath'
      preLoaderRoute: typeof ProjectsProjectPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/AI/$file/$projectPath': {
      id: '/projects/AI/$file/$projectPath'
      path: '/projects/AI/$file/$projectPath'
      fullPath: '/projects/AI/$file/$projectPath'
      preLoaderRoute: typeof ProjectsAIFileProjectPathRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsProjectPathRoute: ProjectsProjectPathRoute,
  ProjectsAIFileProjectPathRoute: ProjectsAIFileProjectPathRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
